version: '3.8'

services:
  redis:
    image: "redis:5.0.6"
    container_name: my-redis
    ports:
      - "6379:6379"
  web:
    build: support/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./support/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev.db
  worker:
    restart: always
    build: support/
    command: celery -A support worker -l info


volumes:
  postgres_data: